name: Release

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  build_and_push:
    name: "Production Registry: us-docker.pkg.dev"
    uses: osinfra-io/github-misc-called-workflows/.github/workflows/build-and-push.yml@3f58f13c9ff1c2c4a94cecad4bab5d3e78d69bce # v0.2.2
    if: github.actor != 'dependabot[bot]'
    with:
      cache_from: type=gha
      cache_to: type=gha,mode=max
      build_args: |
            DD_GIT_REPOSITORY_URL=https://github.com/${{ github.repository }}
            DD_GIT_COMMIT_SHA=${{ github.sha }}
            VERSION=${{ github.event.release.tag_name }}
      registry: us-docker.pkg.dev
      service_account: pt-pneuma-github@pt-corpus-tf16-prod.iam.gserviceaccount.com
      tags: |
        us-docker.pkg.dev/pt-corpus-tf16-prod/pt-pneuma-standard/istio-test:${{ github.event.release.tag_name }}
        us-docker.pkg.dev/pt-corpus-tf16-prod/pt-pneuma-standard/istio-test:latest
      workload_identity_provider: projects/557265520053/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
