name: Release

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  run_go_tests:
    name: "Go: Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
        with:
          go-version: '^1.25'

      - name: Run tests
        run: go test ./...

  build_and_push:
    name: "Production Registry: us-docker.pkg.dev"
    uses: osinfra-io/github-misc-called-workflows/.github/workflows/build-and-push.yml@3f58f13c9ff1c2c4a94cecad4bab5d3e78d69bce # v0.2.2
    if: github.actor != 'dependabot[bot]'
    needs: run_go_tests
    with:
      cache_from: type=registry,ref=us-docker.pkg.dev/pt-corpus-tf16-prod/pt-pneuma-standard/istio-test:latest
      cache_to: type=inline
      build_args: |
            DD_GIT_REPOSITORY_URL=https://github.com/${{ github.repository }}
            DD_GIT_COMMIT_SHA=${{ github.sha }}
            VERSION=${{ github.event.release.tag_name }}
      registry: us-docker.pkg.dev
      service_account: pt-pneuma-github@pt-corpus-tf16-prod.iam.gserviceaccount.com
      tags: |
        us-docker.pkg.dev/pt-corpus-tf16-prod/pt-pneuma-standard/istio-test:${{ github.event.release.tag_name }}
        us-docker.pkg.dev/pt-corpus-tf16-prod/pt-pneuma-standard/istio-test:latest
      workload_identity_provider: projects/557265520053/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
