name: Sandbox

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "**.md"

permissions:
  contents: read
  id-token: write

jobs:
  run_go_tests:
    name: "Go: Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
        with:
          go-version: '^1.25'

      - name: Run tests
        run: go test ./...

  build_and_push_us:
    name: "Sandbox Registry: us-docker.pkg.dev"
    uses: osinfra-io/github-misc-called-workflows/.github/workflows/build-and-push.yml@3f58f13c9ff1c2c4a94cecad4bab5d3e78d69bce # v0.2.2
    if: github.actor != 'dependabot[bot]'
    needs: run_go_tests
    with:
      cache_from: type=gha
      cache_to: type=gha,mode=max
      build_args: |
            DD_GIT_REPOSITORY_URL=https://github.com/${{ github.repository }}
            DD_GIT_COMMIT_SHA=${{ github.sha }}
      registry: us-docker.pkg.dev
      service_account: pt-pneuma-github@pt-corpus-tf16-prod.iam.gserviceaccount.com
      tags: us-docker.pkg.dev/pt-corpus-tf16-prod/pt-pneuma-standard/istio-test:${{ github.sha }}
      workload_identity_provider: projects/557265520053/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
